name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main  # Trigger on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          # Create a virtual environment and activate it
          python3 -m venv venv
          source venv/bin/activate
          
          # Install dependencies from requirements.txt
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with necessary dependencies

      - name: Prepare Lambda deployment package
        run: |
          # Make a directory for the deployment package
          mkdir -p lambda-package

          # Copy the Lambda function code (excluding .git, node_modules, etc.)
          find . -maxdepth 1 -not -name 'lambda-package' -not -name '.git' -not -name 'node_modules' -exec cp -r {} lambda-package/ \;

          # Copy the installed Python dependencies into the lambda-package directory
          cp -r venv/lib/python*/site-packages/* lambda-package/  # Ensure the Python version matches

          # Zip the entire deployment package
          cd lambda-package
          zip -r ../QRCodeGenerator.zip .

      - name: Update Lambda function
        run: |
          # Update Lambda function code with the newly zipped deployment package
          aws lambda update-function-code --function-name QRCodeGenerator \
            --zip-file fileb://QRCodeGenerator.zip  # Replace with your Lambda function name

      - name: Clean up
        run: |
          # Clean up the zip file after deployment
          rm QRCodeGenerator.zip
