name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure Python 3.9 is used

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Create Lambda package
      run: |
        mkdir -p lambda-package
        # Copy only the installed dependencies, not the entire venv folder
        cp -r venv/lib/python3.9/site-packages/* lambda-package/
        
        # Copy the rest of your code (but not the venv directory itself)
        find . -maxdepth 1 -not -name "lambda-package" -not -name "venv" -exec cp -r {} lambda-package/ \;
        
        # Remove the unnecessary venv directory inside the lambda-package folder
        rm -rf lambda-package/venv
        
        # Zip all contents of lambda-package, but exclude lambda-package itself
        cd lambda-package
        zip -r ../lambda-function.zip .

    - name: Upload Lambda package to S3
      run: |
        aws s3 cp lambda-function.zip s3://eventsticket/lambda-function.zip  # Upload to S3

    - name: Deploy Lambda from S3
      run: |
        aws lambda update-function-code \
          --function-name arn:aws:lambda:eu-north-1:465921435493:function:QRCodeGenerator \
          --s3-bucket eventsticket \
          --s3-key lambda-function.zip \
          --region eu-north-1  # Adjust region if necessary
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
