name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main  # Trigger on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout your repository code

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          # Set up Python environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Prepare Lambda deployment package
        run: |
          # Make a directory for the deployment package
          mkdir -p lambda-package

          # Copy the Lambda function and its dependencies to the package directory
          cp -r * lambda-package/
          cd lambda-package

          # Ensure that all dependencies installed in the virtual environment are copied to the deployment package
          cp -r ../venv/lib/python3.x/site-packages/* ./  # Replace python3.x with your actual Python version

          # Zip the entire deployment package
          zip -r ../QRCodeGenerator.zip .

      - name: Update Lambda function
        run: |
          # Update the Lambda function with the new deployment package
          aws lambda update-function-code --function-name QRCodeGenerator \
            --zip-file fileb://QRCodeGenerator.zip  # Replace with your Lambda function name

      - name: Clean up
        run: |
          # Clean up the zip file after deployment
          rm QRCodeGenerator.zip
          rm -rf lambda-package  # Remove the temporary directory
